### PR TITLE
Update configuration options and JS URL

### PR DESCRIPTION
**Pull request by jheth**
Adds the remaining configuration options and updates the JS URL.

### CODE REVIEW

**Review by kiwiupover — APPROVED** [review]
Looks great to me!

Other than the ember 2.12 test failed due to ember 2.14 being installed.

**Comment by jheth** [comment]
This is failing due to https://github.com/ember-cli/ember-try/issues/148

**Comment by kiwiupover** [comment]
@he9qi can we get this merged? 

We would also love to help maintain this project.

**Comment by he9qi** [comment]
Sure, this looks good! 👍

**Comment by he9qi** [comment]
@jheth @kiwiupover, I also invited you guys as collaborators.

**Comment by kiwiupover** [comment]
Thanks heaps mate.

Cheers.

**Comment by jheth** [comment]
@he9qi Do you mind pushing a new version to npm with these changes?

**Comment by he9qi** [comment]
@jheth sure, just did :)

**Pull request merged**
