### PR TITLE
Add a documentation with addon-docs

### PR DESCRIPTION
**Pull request by dcyriller**
This PR aims at adding a documentation site with [addon-docs](https://github.com/ember-learn/ember-cli-addon-docs).

I've split the README content in the different site pages (the dummy app published on github pages).

I noticed that the demo that was pre-existing (in application route and controller) was not working. Probably because of a change on HS side. The url seeems to be invalid. I haven't found an easy-to-use demo on HS. This is why I can't provide a working interactive demo in the doc site 😞.

TODO:
- setup automatic deployment (https://ember-learn.github.io/ember-cli-addon-docs/docs/deploying)
- ~~move options page to esdoc documentation~~

### CODE REVIEW

**Comment by dcyriller** [comment]
Do you think I can merge @he9qi?

To automate the doc deployment, I would need your help. It is done through Travis. Everything is detailed here: https://ember-learn.github.io/ember-cli-addon-docs/docs/deploying#automating-deploys

I do this documentation thing to prepare the migration to hellosign-embedded to [v2](https://github.com/hellosign/hellosign-embedded/releases). It has been released recently. I will be nice to have a doc for the addon before and after the migration.

**Comment by he9qi** [comment]
This looks great! @dcyriller :) merge it whenever you can and I'll setup the automatic deployment.

**Comment by kiwiupover** [comment]
@dcyriller great work mate. 
Shouldn't this be a major version bump?

**Comment by dcyriller** [comment]
We're still in the 0.x versions. So, technically, we didn't have to do a major version bump for [this breaking PR](https://github.com/he9qi/ember-cli-hellosign/pull/7) 😉.

As this PR is adding documentation (with no breaking change), it wouldn't require a major version bump.

That being said, it would be nice to hit a v1 after merging https://github.com/he9qi/ember-cli-hellosign/pull/13. (From that point, I will use the addon in my app btw.) Maybe with a `1.0.0-beta.0`. Wdyt?

Then, we would be able to hit the v2 with `hellosign-embedded` upgrade to v2. (It will contain breaking changes).

**Comment by dcyriller** [comment]
The CI failing job is the one that deploys the doc.

When the setup on Github and Travis sides will be done, I will re trigger it and we´ll be all green again.

**Comment by he9qi** [comment]
I've set up Github and Travis CI with the `DEPLOY_KEY` following https://ember-learn.github.io/ember-cli-addon-docs/docs/deploying#automating-deploys. And I checked the `DEPLOY_KEY` in Travis CI:
screen shot 2019-03-05 at 12 41 52 pm

However, while deploying in Travis CI, it asked for passphrase which the SSH key does not include.
wechat7bef6a74d987e56438d65ac676869308

Have you encountered this before? @dcyriller

**Comment by dcyriller** [comment]
Hey @he9qi, this is unfortunate. But sounds like someone had the same issue. Hopefully, there is a workaround. It is detailed here: https://github.com/ember-learn/ember-cli-addon-docs/issues/294

**Comment by he9qi** [comment]
@dcyriller thanks, that actually worked! 👍 It's green now ;)

**Pull request merged**
