### PR TITLE
Upgrade to ember 3.7

### PR DESCRIPTION
**Pull request by dcyriller**
* Drop node 4 support
* Drop ie 9 support in dummy app
* Opt explicitely into jQuery

### CODE REVIEW

**Comment by dcyriller** [comment]
This is a breaking change 😉

**Comment by dcyriller** [comment]
If this sounds good to you @he9qi, I'd like to remove jQuery in a following PR

**Comment by dcyriller** [comment]
Here a preview of jQuery removal: https://github.com/dcyriller/ember-cli-hellosign/pull/1/

**Comment by he9qi** [comment]
This is good! 👍  Let me merge this PR first :)

**Comment by kiwiupover** [comment]
@dcyriller great to see you over here too. Good work mate!

**Comment by dcyriller** [comment]
Hey @kiwiupover! I was going to create an addon to wrap the code I have in my apps around HelloSign. And I ran into this addon!

**Comment by kiwiupover** [comment]
💯 let's build together. 

Will I see you at EmberConf @dcyriller ?

**Comment by dcyriller** [comment]
No, I won't be able to be there 😞
I hope to make it next year!

**Comment by kiwiupover** [comment]
I know it is a long way to go. You will be missed.

Dave Laird

E: kiwiupover@gmail.com (https://link.getmailspring.com/link/1550518301.local-b10f1005-cc0b-v1.5.6-4cb1851b@getmailspring.com/0?redirect=mailto%3Akiwiupover%40gmail.com&recipient=cmVwbHkrMDAwOWUyMGJlOGI2YTE4NjA2NTk3ZDI4NTA3M2ZiNDc1NjZlZjJkNGM1OWQ4M2ZiOTJjZjAwMDAwMDAxMTg4MmM5ZmU5MmExNjljZTE4ODZhMzczQHJlcGx5LmdpdGh1Yi5jb20%3D)
P: 206 434 2487 (tel:206%20434%202487)
W: http://kiwiupover.com (https://link.getmailspring.com/link/1550518301.local-b10f1005-cc0b-v1.5.6-4cb1851b@getmailspring.com/1?redirect=http%3A%2F%2Fkiwiupover.com&recipient=cmVwbHkrMDAwOWUyMGJlOGI2YTE4NjA2NTk3ZDI4NTA3M2ZiNDc1NjZlZjJkNGM1OWQ4M2ZiOTJjZjAwMDAwMDAxMTg4MmM5ZmU5MmExNjljZTE4ODZhMzczQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Pull request merged**
